# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lobRaAudTHHweOV5NS_vkQOILKdwENfV

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

b=s.split()
print(b)

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("The diameter of {0} is {1} kilometers ".format(planet,diameter))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

array=np.zeros(10)
print(array)

array=np.ones(10)*5
print(array)

"""## 5. Create an array of all the even integers from 20 to 35"""

array=np.arange(20,36,2)
print(array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

Array=np.arange(0,9).reshape(3,3)
print(array)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

m=[1,2,3]
n=pd.DataFrame(m,columns=["Numbers"])
print(n)

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

from pandas.core.indexes.interval import date_range
p=pd.date_range(start='1-01-2023',end='2-10-2023')
print(p)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

g=pd.DataFrame(lists,columns=["sNumber","letter","dno"])
print(g)